### ISSUE TITLE
Contrib librairies fail to deploy

### ISSUE THREAD

**Issue by jchenut** [joeartsea/node-red-heroku#14]
Hi Atsushi,

I found your contribution to the community really great! Thanks for it.

I recently deployed your node-red-heroku repository to Heroku using the Button and found a bug that wasn’t here previously: it’s now impossible to install any contrib librairies, such as node-red-contrib-force, node-red-contrib-postgres-multi, etc.
From the Palette menu, error message is still the same: « Cannot find module… »

Impacted node-red version is v0.20.3
It still works fine with previous version (v0.19.6…)

Apparently, version 0.20 broke something 

Any clues ?
Thanks for your work.
Best regards,
Jérôme

**Comment by joeartsea** [comment]
Thank you for your report. 
The version of Node-RED was fixed at 0.19.6 as a first aid. Look for the root cause.

**Comment by jchenut** [comment]
Thanks for the fast fix!
Strange behavior with v0.20...

**Comment by scropion86** [comment]
hi

i have modified the `package.json` to install latest node-red version as below
```

{
    "name"         : "node-red-heroku",
    "version"      : "0.0.1",
    "dependencies": {
        "when": "~3.x",
        "mongodb": "~2.1.x",
        "nano": "~5.11.0",
        "feedparser":"~0.19.2",
        "redis":"~0.10.1",
        "node-red": "1.0.4"
    }
}
```

but when i try to install any palette i get error below is example to this palette `https://flows.nodered.org/node/node-red-contrib-blynk-api`

and error show

```
2020-03-08T13:24:11.465Z Install : node-red-contrib-blynk-api 0.0.7

2020-03-08T13:24:12.852Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-blynk-api@0.0.7
2020-03-08T13:24:13.759Z [out] + node-red-contrib-blynk-api@0.0.7
2020-03-08T13:24:13.759Z [out] updated 1 package in 0.421s
2020-03-08T13:24:13.779Z rc=0
```

any way to fix it?

**Comment by joeartsea** [comment]
The latest version of Node-RED has been changed to be installed. Does it still happen?

**Comment by joeartsea** [comment]
fix 6d742bb
